##
##  创建 karpenter provisioner
##
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.large"]
    # - key: "karpenter.k8s.aws/instance-category"
    #   operator: In
    #   values: ["c", "m", "r"]
    # - key: "karpenter.k8s.aws/instance-cpu"
    #   operator: In
    #   values: ["4", "8", "16", "32"]
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    Name: "*SubnetPrivate*"
  securityGroupSelector:
    Name: "*sin-eks-cluster*"
  # instanceProfile: KarpenterNodeInstanceProfile
